// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const runtimeEnv = process.env.NODE_ENV?.trim() || "development";
const databaseUrlName = runtimeEnv === "production" ? "DATABASE_URL" : "TEST_DATABASE_URL";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env[databaseUrlName],
  },
});
